### ISSUE TITLE
Why is prod showing version `0.0.0-dev`?

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/ci#22]
![wrong-version](https://user-images.githubusercontent.com/22056320/59611632-a2864900-90e9-11e9-96c3-f4c5f790c98a.png)

Current theory is that one of the branch pipelines deployed over prod. If that's the case, take a crack at making that impossible.

**Comment by vito** [comment]
I don't think any of them actually did the *deploy*, but one of them probably auto-bumped the release repo which then went on to be deployed by the main pipeline: https://github.com/concourse/concourse-bosh-release/commit/53faf0272f9e2221d76be0d6fd2427622f35b7f6

Note the absense of a version number in the commit - different from e.g. https://github.com/concourse/concourse-bosh-release/commit/b5777f4ff32c8220e187cbddc2f0346f88fefcc6

I've since changed the branch pipeline to make the release bumping step manual, which should prevent this from happening again (barring someone actually doing it themselves): https://github.com/concourse/ci/pull/20/commits/1f51b47ec0c32b4a9fccedee1f9d8ab130903aab

...however I haven't checked on any of the existing branch pipelines to make sure they're running the latest .yml. We may have a stray somewhere that needs to be updated.

**Comment by pivotal-jamie-klassen** [comment]
https://ci.concourse-ci.org/teams/main/pipelines/runtime-drills/jobs/bosh-bump/builds/1 is the culprit.
