### ISSUE TITLE
use of concourse/concourse as image in helm-prs-dev/k8s-topgun can be problematic for release candidates

### ISSUE THREAD

**Issue by cirocosta** [concourse/ci#316]
hey,

while working on https://github.com/concourse/concourse-chart/pull/101, a PR that was meant to get us prepared for releasing a version of Concourse that's not released yet, we couldn't get certain tests passing because we'd need to have an RC running, rather than `latest` concourse/concourse.

https://github.com/concourse/ci/blob/5f3a4ca3fd8cd321a17a9f37e4fb10c6ead9f51d/pipelines/helm-prs.yml#L89-L90
https://github.com/concourse/ci/blob/5f3a4ca3fd8cd321a17a9f37e4fb10c6ead9f51d/pipelines/helm-prs.yml#L44-L51

Something that crossed my mind (despite not being sure that this is the *right* solution) is that we could perhaps always take the `image*` values from `values.yaml` and use those as the `image` and `imageTag` for the tests.

This way, for these RC-related PRs, have `values.yaml`' `image` fields pointing to `concourse/concourse-rc`, and regular commits to `master` pointing to the right thing (`concourse/concourse`) so that when the pipeline runs, it'll end up using the right image series. Buuut .. I also realize that this would make us lose the ability to keep track of the image versions used by looking at the build inputs (perhaps something we could display in the beginning of the task run?)

thanks!

**Comment by taylorsilva** [comment]
hmm this is really confusing because (last line)..

https://github.com/concourse/ci/blob/5f3a4ca3fd8cd321a17a9f37e4fb10c6ead9f51d/pipelines/helm-prs.yml#L100-L110

and

https://github.com/concourse/ci/blob/5f3a4ca3fd8cd321a17a9f37e4fb10c6ead9f51d/pipelines/reconfigure.yml#L125-L131

so I _think_ it's using `concourse/concourse-rc` (????!?!)
I think the `CONCOURSE_IMAGE_NAME` param passed into the task is what wins. I think the image we pass into the bucket is not used at all.... makes this very confusing....
