### ISSUE TITLE
improve release notes flow

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/ci#96]
* store release notes in `concourse/concourse`
* write release notes in markdown instead of booklit
* remove any CI pipeline references to `concourse/release-notes`
* destroy the `concourse/release-notes` repo

**Comment by jomsie** [comment]
Thinking about the _new_ flow re: release notes.

Since the release notes md files are in concourse/release_notes, we were thinking of having a `latest.md` file in there, and whenever anyone makes a PR to `concourse/concourse`, they'd also add their release note in there.

Then once it's time to release a new version of concourse, before the `shipit` job, the releng pair will have to copy `latest.md` to `v{version}.md`, clear out `latest.md`, and then make a PR with those changes.
